[tool.poetry]
name = "copwrp"
version = "0.0.1"
description = ""
authors = ["tadamcz <tmkadamcz@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
scipy = "^1.8.1"
numpy = "^1.23.0"
pandas = "^1.4.3"
pytest = "^7.1.2"
statsmodels = "^0.13.2"
pytest-xdist = "^2.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

